"""Grounded question answering over the knowledge graph.

Public function: answer_question(question, graph, llm=None, config=None) -> AnswerResult

Modes (see AnswerResult.mode / llm_used):
    mock    - rule-based summary of retrieved facts, NOT AI generated
    real    - Gemma wrote the answer from retrieved evidence only
    (llm_used=False + error set) - Ollama failed; deterministic retrieval-only summary
"""

from typing import Dict, List, Optional

import networkx as nx
from pydantic import ValidationError

from .config import Config, load_config
from .llm_service import LLMError, LLMService
from .prompts import ANSWER_SYSTEM_PROMPT, build_answer_prompt
from .retriever import retrieve_context
from .schemas import AnswerResult, Provenance, RawAnswer, RetrievalResult, SourceRef, TrailStep

INSUFFICIENT_MESSAGE = "Insufficient evidence in the knowledge graph to answer this question."
MOCK_NOTICE = "[MOCK MODE: rule-based summary of retrieved graph facts; not generated by an AI model.]"
RETRIEVAL_ONLY_NOTICE = "[RETRIEVAL ONLY: the language model was unavailable, so no AI answer was generated.]"


def build_source_index(retrieval: RetrievalResult) -> List[SourceRef]:
    """Number every distinct piece of evidence (S1, S2, ...): trail evidence first."""
    refs: List[SourceRef] = []
    seen: Dict[tuple, str] = {}

    def add(p: Provenance) -> None:
        if p.evidence and p.key() not in seen:
            label = f"S{len(refs) + 1}"
            seen[p.key()] = label
            refs.append(SourceRef(**p.model_dump(), label=label))

    for trail in retrieval.decisions:
        for step in trail.steps:
            for p in step.provenance:
                add(p)
    for p in retrieval.evidence:
        add(p)
    return refs


def _labels_for(step: TrailStep, index: List[SourceRef]) -> str:
    keys = {p.key() for p in step.provenance}
    labels = [r.label for r in index if Provenance(**r.model_dump(exclude={"label"})).key() in keys]
    return ",".join(labels)


def format_trail_text(retrieval: RetrievalResult, index: List[SourceRef]) -> str:
    lines: List[str] = []
    for trail in retrieval.decisions:
        lines.append(f"Decision: {trail.decision_name} (status: {trail.status})")
        for i, step in enumerate(trail.steps, 1):
            refs = _labels_for(step, index)
            lines.append(
                f"  {i}. {step.date_iso or 'undated'} | {step.kind} | {step.description}"
                + (f" [{refs}]" if refs else "")
            )
    return "\n".join(lines)


def format_evidence_text(index: List[SourceRef]) -> str:
    lines = []
    for r in index:
        where = f"doc={r.document_id}, file={r.filename}, page={r.page}, chunk={r.chunk_id}"
        lines.append(f'[{r.label}] ({where}) "{r.evidence}"')
    return "\n".join(lines)


def _extractive_summary(retrieval: RetrievalResult, index: List[SourceRef]) -> str:
    text = format_trail_text(retrieval, index)
    if text:
        return text
    return "\n".join(f"- {r.evidence} [{r.label}]" for r in index[:5])


def _insufficient(question: str, mode: str, model: Optional[str], reason: Optional[str],
                  warnings: List[str]) -> AnswerResult:
    answer = INSUFFICIENT_MESSAGE + (f" ({reason})" if reason else "")
    return AnswerResult(question=question, answer=answer, sufficient_evidence=False, mode=mode,
                        llm_used=False, model=model, warnings=warnings)


def answer_question(
    question: str,
    graph: nx.DiGraph,
    llm: Optional[LLMService] = None,
    config: Optional[Config] = None,
) -> AnswerResult:
    """Answer `question` using only evidence retrieved from `graph`."""
    cfg = config or (llm.config if llm is not None else load_config())
    llm = llm or LLMService(cfg)
    mode = llm.mode
    model = None if llm.is_mock else cfg.model
    question = (question or "").strip()

    warnings: List[str] = []
    graph_modes = list(graph.graph.get("modes", [])) if graph is not None else []
    if not llm.is_mock and any(m != "real" for m in graph_modes):
        warnings.append(
            "Some graph facts were extracted in non-real mode(s): " + ", ".join(sorted(set(graph_modes)))
            + ". They are not AI-verified."
        )

    if not question:
        return _insufficient(question, mode, model, "empty question", warnings)
    if graph is None or graph.number_of_nodes() == 0:
        return _insufficient(question, mode, model, "the knowledge graph is empty", warnings)

    retrieval = retrieve_context(graph, question, config=cfg)
    if not retrieval.sufficient:
        return _insufficient(question, mode, model, retrieval.reason, warnings)

    index = build_source_index(retrieval)
    trail_steps = [s for t in retrieval.decisions for s in t.steps]

    if llm.is_mock:
        answer = MOCK_NOTICE + "\n" + _extractive_summary(retrieval, index)
        warnings.append("Mock mode: answer is rule-based, not AI generated.")
        return AnswerResult(question=question, answer=answer, sufficient_evidence=True,
                            decision_trail=trail_steps, sources=index, mode="mock",
                            llm_used=False, model=None, warnings=warnings)

    def fallback(error: str) -> AnswerResult:
        return AnswerResult(
            question=question,
            answer=RETRIEVAL_ONLY_NOTICE + "\n" + _extractive_summary(retrieval, index),
            sufficient_evidence=True, decision_trail=trail_steps, sources=index,
            mode=mode, llm_used=False, model=model, warnings=warnings, error=error,
        )

    prompt = build_answer_prompt(question, format_trail_text(retrieval, index), format_evidence_text(index))
    try:
        data = llm.generate_json(prompt, system=ANSWER_SYSTEM_PROMPT)
    except LLMError as exc:
        return fallback(f"LLM failure: {exc}")
    try:
        raw = RawAnswer.model_validate(data)
    except ValidationError as exc:
        return fallback(f"model answer had an invalid structure: {exc.errors()[0].get('msg')}")
    if not raw.answer.strip():
        return fallback("model returned an empty answer")
    if not raw.sufficient_evidence:
        return AnswerResult(question=question, answer=raw.answer.strip() or INSUFFICIENT_MESSAGE,
                            sufficient_evidence=False, mode=mode, llm_used=True, model=model,
                            warnings=warnings)

    valid = {r.label for r in index}
    used = [lab for lab in raw.used_sources if lab in valid]
    sources = [r for r in index if r.label in used]
    if not sources:
        sources = index
        warnings.append("The model did not cite valid sources; all retrieved evidence is listed instead.")
    return AnswerResult(question=question, answer=raw.answer.strip(), sufficient_evidence=True,
                        decision_trail=trail_steps, sources=sources, mode=mode, llm_used=True,
                        model=model, warnings=warnings)
